# here you can customize your deployment according to : https://github.com/SocialGouv/actions/blob/master/autodevops-helm-deploy/chart/values.yaml
app:
  enabled: true
  probesPath: /healthz
  containerPort: 8080
