global:
  registry: 10.103.1.205

jobs:
  runs:
    db-keycloak:
      use: SocialGouv/kontinuous/plugins/contrib/jobs/create-db@v1
      ~needs: [app-postgres]
      with:
        pgAdminSecretRefName: pg
        pgSecretName: "keycloak-db-{{ .Values.global.branchSlug32 }}"
        database: "keycloak_{{ .Values.global.branchSlug32 }}"
        pgUser: "keycloak_{{ .Values.global.branchSlug32 }}"
    db-hasura:
      use: SocialGouv/kontinuous/plugins/contrib/jobs/create-db@v1
      ~needs: [app-postgres]
      with:
        pgAdminSecretRefName: pg
        pgSecretName: "hasura-db-{{ .Values.global.branchSlug32 }}"
        database: "hasura_{{ .Values.global.branchSlug32 }}"
        pgUser: "hasura_{{ .Values.global.branchSlug32 }}"
    seed-hasura:
      ~needs: [hasura, app-postgres]
      use: SocialGouv/kontinuous/plugins/contrib/jobs/seed-db@v1
      with:
        seedPath: hasura/seeds/default/books.sql
        pgSecretName: "hasura-db-{{ .Values.global.branchSlug32 }}"

app:
  host: "demo.local"

hasura:
  ~needs: [build-hasura, db-hasura, keycloakx]
  envFrom:
    - secretRef:
        name: "hasura-db-{{ .Values.global.branchSlug32 }}"
    - secretRef:
        name: hasura

keycloakx:
  ~needs: [db-keycloak]
  extraEnvFrom: |
    - secretRef:
        name: "keycloak-db-{{ .Values.global.branchSlug32 }}"
    - secretRef:
        name: keycloak-secrets

deactivate:
  enabled: false
  jobs-deactivate:
    runs:
      deactivate:
        with:
          pgAdminSecretRefName: pg
      drop-db2:
        use: drop-db
        with:
          pgAdminSecretRefName: pg
          database: "hasura_{{ .Values.global.branchSlug32 }}"
