version: "3"

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.0
    environment:
      KC_DB_URL: "jdbc:postgresql://postgres:5432/keycloak"
      KC_DB: postgres
      KC_METRICS_ENABLED: "true"
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_LOG_LEVEL: INFO
    ports:
      - 8080:8080
    depends_on:
      - postgres
    volumes:
      - ./keycloak/config:/opt/keycloak/data/import
      - ./keycloak/providers:/opt/keycloak/providers
    command: "start --import-realm --auto-build --db=postgres --features admin2 --http-enabled=true --http-port=8080 --hostname-strict=false --hostname-strict-https=false"
