jobs:
  runs:
    seed-hasura:
      ~needs: [hasura]
      use: seed-db
      with:
        seedPath: hasura/seeds/default/books.sql
        pgSecretName: "pg-hasura-app"

maildev:
  enabled: true

pgweb-hasura:
  ~chart: pgweb
  ~needs: [app]
  enabled: true
  pgweb:
    envFrom:
      - secretRef:
          name: pg-hasura-app

pgweb-keycloak:
  ~chart: pgweb
  ~needs: [app]
  enabled: true
  pgweb:
    envFrom:
      - secretRef:
          name: pg-keycloak-app
