jobs:
  runs:
    seed-hasura:
      ~needs: [hasura]
      use: seed-db
      with:
        seedPath: hasura/seeds/default/books.sql
        pgSecretName: "pg-hasura-app"

maildev:
  enabled: true

pgweb-hasura:
  ~chart: pgweb
  ~needs: [pg-hasura]
  enabled: true
  pgweb:
    env:
      - name: PGWEB_DATABASE_URL
        valueFrom:
          secretKeyRef:
            name: pg-hasura-app
            key: DATABASE_URL
      - name: PGWEB_AUTH_USER
        value: admin
      - name: PGWEB_AUTH_PASS
        valueFrom:
          secretKeyRef:
            name: pgweb
            key: PGWEB_PASSWORD

pgweb-keycloak:
  ~chart: pgweb
  ~needs: [pg-keycloak]
  enabled: true
  pgSecretName: pg-keycloak-app
