jobs:
  runs:
    db-keycloak:
      use: SocialGouv/kontinuous/plugins/contrib/jobs/create-db@v1
      with:
        pgAdminSecretRefName: pg-scaleway
        pgSecretName: "keycloak-db-{{ .Values.global.branchSlug32 }}"
        database: "keycloak_{{ .Values.global.branchSlug32 }}"
        pgUser: "keycloak_{{ .Values.global.branchSlug32 }}"
    db-hasura:
      use: SocialGouv/kontinuous/plugins/contrib/jobs/create-db@v1
      with:
        pgAdminSecretRefName: pg-scaleway
        pgSecretName: "hasura-db-{{ .Values.global.branchSlug32 }}"
        database: "hasura_{{ .Values.global.branchSlug32 }}"
        pgUser: "hasura_{{ .Values.global.branchSlug32 }}"
    db-metabase:
      use: SocialGouv/kontinuous/plugins/contrib/jobs/create-db@v1
      with:
        pgAdminSecretRefName: pg-scaleway
        pgSecretName: "metabase-db-{{ .Values.global.branchSlug32 }}"
        database: "metabase_{{ .Values.global.branchSlug32 }}"
        pgUser: "metabase_{{ .Values.global.branchSlug32 }}"
    seed-hasura:
      ~needs: [hasura]
      use: SocialGouv/kontinuous/plugins/contrib/jobs/seed-db@v1
      with:
        seedPath: hasura/seeds/default/books.sql
        pgSecretName: "hasura-db-{{ .Values.global.branchSlug32 }}"

hasura:
  ~needs: [build-hasura, db-hasura, keycloakx]
  envFrom:
    - secretRef:
        name: "hasura-db-{{ .Values.global.branchSlug32 }}"
    - secretRef:
        name: hasura

pgweb:
  envFrom:
    - secretRef:
        name: "hasura-db-{{ .Values.global.branchSlug32 }}"

metabase:
  envFrom:
    - secretRef:
        name: "metabase-db-{{ .Values.global.branchSlug32 }}"

keycloakx:
  ~needs: [db-keycloak]
  extraEnvFrom: |
    - secretRef:
        name: "keycloak-db-{{ .Values.global.branchSlug32 }}"
    - secretRef:
        name: keycloak-secrets

deactivate:
  enabled: false
  jobs-deactivate:
    runs:
      deactivate:
        with:
          pgAdminSecretRefName: pg-scaleway
      drop-db2:
        use: drop-db
        with:
          pgAdminSecretRefName: pg-scaleway
          database: "hasura_{{ .Values.global.branchSlug32 }}"
