jobs:
  runs:
    seed-hasura:
      ~needs: [hasura]
      use: seed-db
      with:
        seedPath: hasura/seeds/default/books.sql
        pgSecretName: "pg-hasura-app"

maildev:
  enabled: true

pgweb-hasura:
  ~chart: pgweb
  ~needs: [pg-hasura]
  enabled: true
  pgSecretName: pg-hasura-app

pgweb-keycloak:
  ~chart: pgweb
  ~needs: [pg-keycloak]
  enabled: true
  pgSecretName: pg-keycloak-app

pg-hasura:
  ~chart: pg
  backup:
    name: new-backups4
  recovery:
    enabled: true
    targetTime: "2023-09-18T15:45:33"

  # pg-hasura2:
  #   ~chart: pg
  #   backup:
  #     name: new-backups3
  #   recovery:
  #     name: new-backups2
  #     serverName: pg-hasura

  cnpg-cluster:
    recovery:
      enabled: true

    #  targetTime: "2023-09-18T15:45:33"
