jobs:
  runs:
    db-keycloak:
      use: create-db
      with:
        pgSecretName: "keycloak-db"
        database: "keycloak_{{ .Values.global.branchSlug32 }}"
        pgUser: "keycloak_{{ .Values.global.branchSlug32 }}"
    db-hasura:
      use: create-db
      with:
        pgSecretName: "hasura-db"
        database: "hasura_{{ .Values.global.branchSlug32 }}"
        pgUser: "hasura_{{ .Values.global.branchSlug32 }}"
    seed-hasura:
      ~needs: [hasura]
      use: seed-db
      with:
        seedPath: hasura/seeds/default/books.sql
        pgSecretName: "hasura-db"

hasura:
  ~needs: [build-hasura, db-hasura, keycloakx]
  envFrom:
    - secretRef:
        name: "hasura-db"
    - secretRef:
        name: hasura

keycloakx:
  ~needs: [db-keycloak]
  extraEnvFrom: |
    - secretRef:
        name: "keycloak-db"
    - secretRef:
        name: keycloak-secrets

deactivate:
  enabled: false
  jobs-deactivate:
    runs:
      deactivate:
        with:
          db: true
      drop-db2:
        use: drop-db
        with:
          database: "hasura_{{ .Values.global.branchSlug32 }}"
