jobs:
  runs:
    db-keycloak:
      use: create-db
      with:
        pgAdminSecretRefName: pg-scaleway
        pgSecretName: "keycloak-db-{{ .Values.global.branchSlug32 }}"
        database: "keycloak_{{ .Values.global.branchSlug32 }}"
        pgUser: "keycloak_{{ .Values.global.branchSlug32 }}"
    db-hasura:
      use: create-db
      with:
        pgAdminSecretRefName: pg-scaleway
        pgSecretName: "hasura-db-{{ .Values.global.branchSlug32 }}"
        database: "hasura_{{ .Values.global.branchSlug32 }}"
        pgUser: "hasura_{{ .Values.global.branchSlug32 }}"
    seed-hasura:
      ~needs: [hasura]
      use: seed-db
      with:
        seedPath: hasura/seeds/default/books.sql
        pgSecretName: "hasura-db-{{ .Values.global.branchSlug32 }}"

hasura:
  ~needs: [build-hasura, db-hasura, keycloakx]
  envFrom:
    - secretRef:
        name: "hasura-db-{{ .Values.global.branchSlug32 }}"
    - secretRef:
        name: hasura

keycloakx:
  ~needs: [db-keycloak]
  extraEnvFrom: |
    - secretRef:
        name: "keycloak-db-{{ .Values.global.branchSlug32 }}"
    - secretRef:
        name: keycloak-secrets

jobs-deactivate:
  enabled: false
  runs:
    deactivate:
      use: deactivate
      with:
        pgAdminSecretRefName: pg-scaleway
    drop-db:
      use: drop-db
      with:
        pgAdminSecretRefName: pg-scaleway
        database: "keycloak_{{ .Values.global.branchSlug32 }}"
    drop-db2:
      use: drop-db
      with:
        pgAdminSecretRefName: pg-scaleway
        database: "hasura_{{ .Values.global.branchSlug32 }}"
