jobs:
  runs:
    seed-hasura:
      ~needs: [hasura]
      use: seed-db
      with:
        seedPath: hasura/seeds/default/books.sql
        pgSecretName: "pg-hasura-app"

maildev:
  enabled: true

pgweb-hasura:
  ~chart: pgweb
  ~needs: [pg-hasura]
  enabled: true
  pgSecretName: pg-hasura-app

pgweb-keycloak:
  ~chart: pgweb
  ~needs: [pg-keycloak]
  enabled: true
  pgSecretName: pg-keycloak-app
# pg-hasura:
#   ~chart: pg
#   backup:
#     name: new-backups
#   cnpg-cluster:
#     recovery:
#       enabled: true
#       targetTime: "2020-11-26 15:22:00.00000+00"
