jobs:
  runs:
    seed-hasura:
      ~needs: [hasura]
      use: seed-db
      with:
        seedPath: hasura/seeds/default/books.sql
        pgSecretName: "pg-hasura-app"

maildev:
  enabled: true

pgweb-hasura:
  ~chart: pgweb
  ~needs: [pg-hasura]
  enabled: true
  pgSecretName: pg-hasura-app

pgweb-keycloak:
  ~chart: pgweb
  ~needs: [pg-keycloak]
  enabled: true
  pgSecretName: pg-keycloak-app

# 1ere version
# pg-hasura:
#   ~chart: pg
#   backup:
#     enabled: true

# 2eme version
# pg-hasura:
#   ~chart: pg
#   backup:
#     enabled: true
#     name: restore-from-20h03-6
#   cnpg-cluster:
#     recovery:
#       enabled: true
#       #targetTime: "2023-09-18T20:00:00"

# 3eme version
pg-hasura:
  ~chart: pg
  backup:
    enabled: true
    name: restore-from-20h03-7
  recovery:
    name: restore-from-20h03-6
  cnpg-cluster:
    recovery:
      enabled: true
      targetTime: "2023-09-20T08:00:00"
