jobs:
  runs:
    build-app:
      use: SocialGouv/kontinuous/plugins/fabrique/jobs/build@v1
      with:
        imageProject: fabrique
        imageRepository: template
        imagePackage: app
        registrySecretRefName: harbor
        buildArgs:
          NEXT_PUBLIC_APP_VERSION_COMMIT: "{{ $.Values.global.sha }}"
          NEXT_PUBLIC_HASURA_GRAPHQL_ENDPOINT_URL: "https://hasura-{{.Values.global.host}}/v1/graphql"
    db-keycloak:
      use: SocialGouv/kontinuous/plugins/fabrique/jobs/create-db@v1
      with:
        pgAdminSecretRefName: pg-scaleway
        pgSecretName: "keycloak-db-{{ .Values.global.branchSlug32 }}"
        database: "keycloak_{{ .Values.global.branchSlug32 }}"
        pgUser: "keycloak_{{ .Values.global.branchSlug32 }}"
    db-hasura:
      use: SocialGouv/kontinuous/plugins/fabrique/jobs/create-db@v1
      with:
        pgAdminSecretRefName: pg-scaleway
        pgSecretName: "hasura-db-{{ .Values.global.branchSlug32 }}"
        database: "hasura_{{ .Values.global.branchSlug32 }}"
        pgUser: "hasura_{{ .Values.global.branchSlug32 }}"

hasura:
  needs: [build-app, build-hasura, db-hasura]
  envFrom:
    - secretRef:
        name: "hasura-db-{{ .Values.global.branchSlug32 }}"

keycloakx:
  needs: [build-app, db-keycloak]
  extraEnvFrom: |
    - secretRef:
        name: "keycloak-db-{{ .Values.global.branchSlug32 }}"
    - secretRef:
        name: keycloak-secrets

jobs-deactivate:
  enabled: false
  runs:
    deactivate:
      use: SocialGouv/kontinuous/plugins/fabrique/jobs/deactivate
      with:
        pgAdminSecretRefName: pg-scaleway
    drop-db:
      use: SocialGouv/kontinuous/plugins/fabrique/jobs/drop-db
      with:
        pgAdminSecretRefName: pg-scaleway
        database: "keycloak_{{ .Values.global.branchSlug32 }}"
    drop-db2:
      use: SocialGouv/kontinuous/plugins/fabrique/jobs/drop-db
      with:
        pgAdminSecretRefName: pg-scaleway
        database: "hasura_{{ .Values.global.branchSlug32 }}"
