kind: ConfigMap
apiVersion: v1
metadata:
  name: app
data:
  NEXT_TELEMETRY_DISABLED: "1"
  KEYCLOAK_URL: "https://keycloak-{{.Values.global.host}}/realms/app-realm"
  NEXTAUTH_URL: "https://{{.Values.global.host}}"
