apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: franceconnect
spec:
  encryptedData:
    FRANCE_CONNECT_CLIENT_ID: AgCbLEqJcxaUphThDCEtuwLv6tGCVWn5pGADStG7x+yx7w2OQ2Ucdr9srt7Zev5GH4RIu+t3WY/LEcNXkxnJWraPYPsON5iQ0zj8R2UJIpv/kmLixOTaeLxBODknpSoVSUehOKCHVtqggLCTVPAJNSJgR2cDebW3bH8w9uvAgX1fXu0weLIjm5q815iwbeQmkEXejkWuGYALfwa08YlexbMmTg/HDGNl7T843XGZjNbPO4rRwfjEAYkA30WxJ7hSxOhqZTDBJT/agWoxei5QvNykm/wU88pr6Ume7wmMGG/vizWfRweXkiGuWF687Nt1xq+SEAGK/GZuujHIp3VbHPI0CIfjU0NrTK4qpCp7bDl3rdvdzx6a5ubNjhv0Z3dwF+Y1UFyB5NIWkpJn8qxa060I5fFWbvw4xe7kJTufx8jVL7h8HQK1iCw2DEhx4M3L0KslpNby6OFSUINTdZhDbj9/l5tBMrxbtxsnubxbuUvCBSurI6iNUrEXu4pruaN4VautwkN1M1EHMtMxE+PzpoV61GMdGwZmrfZzOrLYYXdKaCAcRNAGOo156wapdk7QBNqK6GrbGbsaIJo0QruVebPS36rmgsc+0JDKYruIvcA94wkbzvScy0RwiSpfqBhcUHZXq2dCRhgrkJnFfXJbpKziVGcvQmMYPQEH78jJgzswdoK2tCZnxg4jXSJv6pn+2BWmAAMvMRXT3Zb+styCVkODPwcgvIcl6h9VgaTyc4Tu+kjKkHvQS6Age0/9M0W5Z9/4ngzJQNzDxl0PU+oGckiJ
    FRANCE_CONNECT_CLIENT_SECRET: AgAq5ZXB3fz9RjjI/bE0I92LcxwNTVih56O8n7xxoxzea10nsV+6Tu76vjE8znLw71QobQeLnuoI61WcSl1f0NBQwl5fIGDSRjCgSUAz1+2T4NF7Q1b9wqIsAsC4dvMMSiNF19P+4/galSbwxJ5qWVjmYt3iC3hBrgs1nuaFVDUlo1X9Qwi9eutFnjesZIcT4WnlU7onSlTQgmshUUfc2IBcgLYWftl35dhIvXKifka2tUTiCsJkLjfmOrKYtfOfw1a4MOCn74LMhzoZNAUFHwlJRZTw+PbAWFKz+Z/5wvEDB1pevU8j5Kdg6qgCwrExCsHFGxsg46Io6HChH0ktIWxaPV7U1Xx0h8VxOo2VgStQq1pWEy3hq3BVxiVGTgywhPtwWhJWWlFCcrnO7Za9nZtYmtM+DSUlbrGQdSK9Z1U5kpeJdLpNe72oPZ/hJ5Fl6i4kO6iH6xDnKfgjZpU1OeL9tpa5Dpujp+chQNFVI8+7nZY389Z53NxGEMMRWS42JH0N+yejtVZsHipfo9s/Y4TdaR7cjoKHnvHi+rVo8TI3NwwEvQBRmT2dHX1XXOz5O4hx30gy3XHqCYaX5i9evXexy5xRXL3lpQqfx3VmFf7eJEC/AJrvdMxwhDnzaq2lxjgRfx38ty5wKy+EFvsBFAf0hKtnmlwO0Vpz78Zuj5t+GeJ4exYHwUA7NVwOVzqbwwsZctM7kTNc99DxSg68MsSDsZcXiWhNL5J9PowD38fG/fXHiOpb3TxSSwVTIR7OzozZ3fYpRQ6gbgQiFOHnSZmk
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: franceconnect
    type: Opaque
