kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: keycloak-secrets
  
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  template:
    metadata:
      name: keycloak-secrets
      
      creationTimestamp: null
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
    type: Opaque
  encryptedData:
    KEYCLOAK_ADMIN: AgCH+7OBepTzHZ7eqCQzzUkUj0kv6aS8RAirf1dRMKvSdCv7Lh1cBPsUJJS0KPbVP0FV5iAzvraVVwMjFB+oIUdY7iBtUbXF540YQziV2G2M9MksSNwQ3szKVcJ6vxOPdxW4s9OnNqhVVcusKQDONcOn5VTzBaECtyntFNaxPK7yijMIZq+3GFx2leLMS0wvGdL17K67iLUovUNFSQVQfbuhyXXCY67/f69+xah/1pXPXgZ8EyauctQrJgKnxhO482Jr+eBASgpNTR9cIu71hErRjF1FUlKOWb61JAo8sERSUmoVxyVm4tjJw//wx/U6KJXWMQP9yTKpMID/+M/7wTjZyXkkO2vJUF55Rx2tGbxcTsPSzoStzlxdxG1DWBEOBlFkwdj19S1wSuJQVmC2f05G1tFvtMtE0g1Y2nTkBLFwdpminZ9iJeXYqzfVc5q3tjpeYhdeSD3FjDAT6ngD08mof6SqOqIYCr4OmIP/EXSAMFOeP+yvYQZ5TCFzNX0wcDcN46nVg0RtYhlJCPDY4RiBtYMY7oWQ6oT3wQeV0dcIbJCjEC6SRExhBB6rKrd9woIKHR/Dkur0wr7BIIv6kqCxGa48FbG5StSrhVjUAF3F5zux/s6faIRNX2Hgcac+2elZnz5DhCh31g+kIxyU8Q1jtYLQ8vQ1hajqiVl4+PFMcZz4TB8OF2V/d+ejECZuVe15h54XakO0brw1jH7uukFzHlVsNnPCfFGcV2VsFVesjlOxSTm5qoN6+Nl/fQ==
    KEYCLOAK_ADMIN_PASSWORD: AgAphXAKSVZMs0d5AI5cT4M4ZfquHZTexaFJajT6E+PwqF0XfdvN4lS/DkIhB+UhapS73xEGRd3evhNgIAJWUS2xrhNLoIFG8me8NpbwbT1Hb/qV8A69biqtY/i13An8z8o8IbhausXCtGE6jRopDiI1yBCo3+TbZ53pd2Ps8FBKrJ8tHwlD3QXDX6rFezA7NnUAuOVu0zGq6onvYeq9WOvJrMw3D45a14964Bw/yPEZIKe520PbVOdgGqqSXLf0k31xvj7CAhDT4woah/8WnLjFRZ+Dhb8y5azaRBdSRXsLcqd9qQckk7fOBCiiaTdZMBmGMgeNd2X/tOQJqxcizJO0FLvlUy36TRu+MduEs8fnqcnpwgtA6M7o+H++yVGMARTjMue6vvzOOr46zKjS+DLVzP2mwChq3OOT+DmlXaAhnbk/sIM/Pl0johiywqC4F5jltmO2szecMgyBP1R4qkICm42wR2GUoriji+OxQuPtj9Z+cytSPqFtq7eqv4nMkQIZCXAKhRpe3EMi9G5ceG2T7yyLemikzbnd1Dp1dDWh0jMDj8b3cQWFyw9Ttda6elKUt/nabVAU8cDu1BAZvD8rVUMy/rGrMTiLfbjQM/SWC1+4TNd2i/aY/pSkKFlkLbFFMmFsckfD62u6hu+jQfh2HiOEOGgPsmkj4IPR9FnfKE9lCVKDvRlqM7jh+bpWSYLn4mRJKdUfGZfGYeCHVdwUy7CQuyubWp2l5R6dHOkWG1fsOiESPhZHlHiaYg==
