keycloakx:
  ingress:
    annotations:
      cert-manager.io: cluster-issuer
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/tls-acme: "true"
    tls:
      - hosts:
          - "keycloak-{{ .Values.global.host }}"
        secretName: keycloak-crt

jobs:
  runs:
    build-app:
      with:
        buildArgs:
          PRODUCTION: "true"
          NEXT_PUBLIC_IS_PRODUCTION_DEPLOYMENT: "true"
# # Restore a PG instance from a backup
# pg-hasura:
#   ~chart: pg
#   backup:
#     enabled: true
#     name: new-instance-name
#   cnpg-cluster:
#     recovery:
#       enabled: true
#       targetTime: "2023-09-18T20:00:00"
# # Optional: recover from some other instance
#   recovery:
#     name: some-instance-name
