/* eslint-disable */
//prettier-ignore
module.exports = {
name: "@yarnpkg/plugin-fetch",
factory: function (require) {
var plugin=(()=>{var ce=Object.defineProperty;var ae=(n,t,e)=>t in n?ce(n,t,{enumerable:!0,configurable:!0,writable:!0,value:e}):n[t]=e;var c=(n=>typeof require<"u"?require:typeof Proxy<"u"?new Proxy(n,{get:(t,e)=>(typeof require<"u"?require:t)[e]}):n)(function(n){if(typeof require<"u")return require.apply(this,arguments);throw new Error('Dynamic require of "'+n+'" is not supported')});var a=(n,t)=>()=>(t||n((t={exports:{}}).exports,t),t.exports);var u=(n,t,e)=>(ae(n,typeof t!="symbol"?t+"":t,e),e);var w=a((Ke,D)=>{"use strict";D.exports=function(t){return t.map(function(e){return e&&typeof e=="object"?e.op.replace(/(.)/g,"\\$1"):/["\s]/.test(e)&&!/'/.test(e)?"'"+e.replace(/(['\\])/g,"\\$1")+"'":/["'\s]/.test(e)?'"'+e.replace(/(["\\$`!])/g,"\\$1")+'"':String(e).replace(/([A-Za-z]:)?([#!"$&'()*,:;<=>?@[\\\]^`{|}])/g,"$1\\$2")}).join(" ")}});var B=a((We,A)=>{var C=c("fs"),ie=c("path"),{parseSyml:le}=c("@yarnpkg/parsers");A.exports=function(){let t=C.readFileSync("yarn.lock","utf8"),e=le(t),o=Object.keys(e).filter(r=>r.includes("@workspace:")),s=o.map(r=>{let[,i]=e[r].resolution.trim().split("@workspace:");return i==="."?null:i}).filter(Boolean);o.forEach(r=>{let{dependencies:i,dependenciesMeta:l,peerDependencies:q,peerDependenciesMeta:b,resolution:O,bin:ne}=e[r],[oe,P]=O.trim().split("@workspace:"),re=ie.join(P,"package.json"),h={name:oe,version:"0.0.0",description:"**DON'T COMMIT** Generated file for caching",private:!0,dependencies:i,peerDependencies:q,peerDependenciesMeta:b,bin:ne};if(l){let g={};Object.keys(l).forEach(m=>{g[m]=i[m],delete i[m]}),h.optionalDependencies=g}if(P==="."){s.length>0&&(h.workspaces={packages:s});let g=Object.keys(e),m=p=>{let d=p.trim().split("@");return p.startsWith("@")?d=d.slice(0,2):d=d.slice(0,1),d.join("@")};h.resolutions=g.filter(p=>{if(p.includes("@workspace:")||p.includes(", ")||!p.includes("@npm:"))return!1;let d=m(p);return g.every(y=>p===y?!0:y.split(",").map(k=>m(k)).every(k=>k!==d))}).reduce((p,d)=>{let[y,k]=d.trim().split("@npm:");return p[y]=k.includes("@")?`npm:${k}`:k,p},{})}C.mkdirSync(P,{recursive:!0}),C.writeFileSync(re,`${JSON.stringify(h,null,2)}
`)})}});var j=a((_e,Y)=>{var pe=B();Y.exports=n=>{n.context.stdout.write(`[YARN-FETCH] extracting package.json file(s) from yarn.lock
`),pe()}});var R=a((Ge,H)=>{var f=c("fs"),ue=c("path"),{execSync:de}=c("child_process"),{parseSyml:ke}=c("@yarnpkg/parsers"),{BaseCommand:fe}=c("@yarnpkg/cli"),{Command:me,Option:v}=c("clipanion"),ge=w(),he=j(),x;H.exports=(x=class extends fe{protectPackageJson=v.Boolean("--protect-package-json");args=v.Proxy();async execute(){let{protectPackageJson:t=process.stdout.isTTY}=this,e=[];if(t){this.context.stdout.write(`[YARN-FETCH] backup possible package.json file(s)
`);let s=f.readFileSync("yarn.lock","utf8"),r=ke(s);e=Object.keys(r).filter(l=>l.includes("@workspace:")).map(l=>{let{resolution:q}=r[l],[,b]=q.trim().split("@workspace:");return ue.join(b,"package.json")}),e.forEach(l=>{f.existsSync(l)&&!f.existsSync(`${l}.yarn-plugin-fetch-bak`)&&f.copyFileSync(l,`${l}.yarn-plugin-fetch-bak`)})}he(this);let o=`yarn ${ge(this.args)}`;this.context.stdout.write(`[YARN-FETCH] ${o}
`);try{de(o,{stdio:"inherit"})}catch(s){throw s}finally{t&&(this.context.stdout.write(`[YARN-FETCH] restoring possible package.json file(s)
`),e.forEach(s=>{f.existsSync(`${s}.yarn-plugin-fetch-bak`)?f.renameSync(`${s}.yarn-plugin-fetch-bak`,s):f.unlinkSync(s)}))}}},u(x,"paths",[["fetch"]]),u(x,"usage",me.Usage({description:"fetch dependencies from yarn.lock in Docker build",details:`
      expand yarn.lock to package.json file(s) and install dependencies in Docker build.
    `,examples:[["yarn fetch --immutable","yarn fetch workspace my-package focus"]]})),x)});var M=a((Qe,L)=>{var{BaseCommand:ye}=c("@yarnpkg/cli"),xe=j(),S;L.exports=(S=class extends ye{async execute(){xe(this)}},u(S,"paths",[["fetch-tools","expand-lock"]]),S)});var K=a((Xe,I)=>{function qe(n,t,e){let o=t.split("."),s=n;for(let r of o){if(s[r]===void 0)return e;s=s[r]}return s}function be(n,t,e){let o=t.split("."),s=n;for(let r=0;r<o.length-1;r++){let i=o[r];(!s[i]||typeof s[i]!="object")&&(s[i]={}),s=s[i]}return s[o[o.length-1]]=e,n}function Pe(n,t){let e=t.split("."),o=n;for(let s=0;s<e.length-1;s++){let r=e[s];if(!o[r])return!1;o=o[r]}return delete o[e[e.length-1]],!0}I.exports={get:qe,set:be,unset:Pe}});var F=a((et,_)=>{var W=c("fs"),{get:we,set:Ce,unset:je}=K();_.exports=function(t,e){let o=JSON.parse(W.readFileSync("package.json","utf-8")),s=we(o,t);s!==void 0&&(Ce(o,e,s),je(o,t),W.writeFileSync("package.json",JSON.stringify(o,null,2)))}});var $=a((tt,z)=>{var Se=F();z.exports=function(){Se("scripts._postinstall","scripts.postinstall")}});var U=a((nt,G)=>{var{BaseCommand:Fe}=c("@yarnpkg/cli"),$e=$(),E;G.exports=(E=class extends Fe{async execute(){$e()}},u(E,"paths",[["fetch-tools","disable-postinstall"]]),E)});var J=a((rt,Z)=>{var Ee=F();Z.exports=function(){Ee("scripts.postinstall","scripts._postinstall")}});var V=a((at,Q)=>{var{BaseCommand:Je}=c("@yarnpkg/cli"),Ne=J(),N;Q.exports=(N=class extends Je{async execute(){Ne()}},u(N,"paths",[["fetch-tools","disable-postinstall"]]),N)});var te=a((pt,ee)=>{var{execSync:Te}=c("child_process"),{BaseCommand:Oe}=c("@yarnpkg/cli"),{Option:X}=c("clipanion"),De=w(),Ae=$(),Be=J(),T;ee.exports=(T=class extends Oe{postinstall=X.Boolean("--postinstall");args=X.Proxy();async execute(){this.postinstall||(this.context.stdout.write(`[YARN-FETCH] disable postinstall command in package.json
`),Be());let t=`yarn workspaces focus --production ${De(this.args)}`;this.context.stdout.write(`[YARN-FETCH] ${t}
`),Te(t,{stdio:"inherit"}),this.postinstall||(this.context.stdout.write(`[YARN-FETCH] re-enable postinstall command in package.json
`),Ae())}},u(T,"paths",[["fetch-tools","production"]]),T)});var Me=a((dt,se)=>{var Ye=R(),ve=M(),He=U(),Re=V(),Le=te();se.exports={commands:[Ye,ve,Re,He,Le]}});return Me();})();
return plugin;
}
};
