kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: franceconnect
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  template:
    metadata:
      name: franceconnect
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
    type: Opaque
  encryptedData:
    FRANCE_CONNECT_CLIENT_ID: AgBHBuXV3/X3GgTmRHOvLXo2J9HJj5R91uhdMzXyeW6iulWVM2gKQle/TTsT2nyKjxk6OZr8Z5AvZq2M3mL8BnuAXdiz3V78LGbBzyZ9yB9ndb/vyHzhR5LEputZ0aX2sBLzho4DPwa/Vwd/h1VUAn9vDaACF3bZqg2MVejeE6lTpFtbmExSWCqg2TtWjjr8SXmG2RI83Cwnoq7QWAGhveTVa3DfTZf//bm9swXqfmiNUxKxKJSbW9FeYByECXWhCb181JB9Z52dxMHycwBXULhxVtWNj0jIsH1bMt0SgWjvkrVY7lzFL8ZuzcR+7+/BOT0bkAlfZf4LL7QpC0Y+IOJyxUPmDhmRHv46yrGMxnJRxglFpztXSs5n5haKvHKStW7dvuZse55TTztKheV+MQWJpaPbHrIvPsf10R/C7oWba1HdX+CWcE8Qcxr76+P0GQfMJrilif68LwtDM/3L6C6ivFscGuzPGXMxPfY3fpc+2+A+bGBHWoP42JvoAnR9ms8KCi0HRNqaFooe6/tFvdAG3eXiHFIg3SFwOGGQq9eDOWomP1RMjCH3/2JQkKIRdGxxwU81Wj0wnIRjn8Zbg2jENlrYsjovvdz4EwHEDQKSyEpM+wb9gghKf+NsprJT979HtDB4rHysOb8FuooG8uzjp5Bl1QsYWQKD2z2b2e23MTWcB0lKEUUBuKtef5dnRmYcS6kcboz85KAjdozFlQg++RPoY5UEPzxVCyB0ltpgkgd7cSWhozPaqV7nu83GIzRmisrsvAg99e3ulwFjUA1t
    FRANCE_CONNECT_CLIENT_SECRET: AgCMWzfW57Sqd3pdtFcyFMI3h7ojDw/+u4g0uQJeIzxMpiiwdBTrkQyD6kXoyjHThu8zOYFVpTuZejSievKT8EnZKF12MtqS8I4IqWV14FscXEj3sTVhpIFgVAO+iI7fsgIBV2f0ouGrziDm0EKvthJ2TKPCL+j2BBf9bQxMYRJJpO/abgg101n5tgk6OZiTv9ZcKkk2S/W+qUCbbIdEdmNqJSEBkzm/eQFRXHqCgrFFukOo14AThkC+IRCbH2UNaHd5aBLYiYvKS4ToxmLvG+tkXpy/tnEwQZYKV3HjtlbNbCh1M9uZLs5HV6PCzV2doJ+gjVsS30RAtyt1XPDKMMpof+2K7PAfXEmx7kIaoiQt1OkcjU83iXM7tziT7Ot4wUMysRTsYVgNHypFgpHYNOBlM0zzn2cxtaVgsuQMMXncaxD/yhBuu7Y36gY21l2O9BlyDaq8MY5jGhww3lj6gNHkG35VRrgXYNlLdNzWpH4cePxH6v0yO5YtUvKgZwJ9zO+M4pZyS+K9mIFejfy3AU+ms76YnDIhLtNqUc6g2yA5tqZBXCEs7DdIkXWWzZ0RGO0tatpg4GuA/B0EyheiannM+qEYNL9fc2Zj81dBWJDyCJlcoFZCGbTp1FN0oEaBCquWcixqiB+/RNFntJWpjzSBysKfuhuKJM0sP/Rg7JWT7Sr48x1MPBRB6DnLLitxWxoqn+vx0YCPFnXIM2ie65WdlSa/YYIWk0EZq2/gwtfrhhnlIjrsosF8wFGhZrZVeY/c29IGQt5Ca0yX1XWbtFQJ
