kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: hasura
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  template:
    metadata:
      name: hasura
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
    type: Opaque
  encryptedData:
    HASURA_GRAPHQL_ADMIN_SECRET: AgAZ/q8ca95usLPqh9zR2DitMmZa9+UyBM+tovdPJYhqHAXYAuuOto/p80Lr9hcheZMCbjPFhrxG7WJmEvbKBXunYmfDIrmN1ipW5MUyg6wZZ7EsKCtnmov0dxueT8iRbEKkeCb3Ju16tVspewy7cvoYTLnhlhM2j9hVK/0bJ6jBXZ4clXKj7SvadQHEU0TpThThc4rKte5gWMSeJEVv7Mlgako/NvcSMbexhd4NJw+3O08nCix1VGGRbhukkRGXvJ6Fn8jxxvs7MbSqIZn3omiNEitfc2lAxwl0pUEoN6Ymos83Z5OBFhAVX4q1DkR7j1MdTChAgtIas4daRf1jx034d/jEoBbu5TBflSYq5kABe79Lw9tCdtdDouqg+u1jYtW8HSujIzRg7TFImIJQL7zL9/KRbjs4y/Cwdwn9pztvCdKn3MqAlex+Qky8ueSAQFO021FXY3iFIp7me3r+GhuyBp6IN8Z+ykUbGw1jac8mVjFH+Xo7QZJtzL6dQfMOA36O3QOnSABBqvMII/r+HtjGKvzAfqhGmzi9JddgZUrUWVuyXKRgcUjbSSzjEn0W2oDWD3TSxroKknKmH2Et5NQxjkf68wwZjADB4GLnX9bi8knUnKYT+9sY0Sy0ZFD4DXSnzYd421YojN9FF7b1xJtYKpK6j7qGue+Ra+zNt1P4lYl11OGR7MsQ8TDiG2lw50TrHHk9JEQCtUnb9fJo2sF8SlRu
