apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: hasura
spec:
  encryptedData:
    HASURA_GRAPHQL_ADMIN_SECRET: AgBt4ZhbUhFLU7DZocGxxVVZZsHB7nPbkoJiIAwiJRaxu+LgcV6EbR4dH80UqXJYurjEGybGmB5MzL9EWoRT/cfNTFxEpy7uo9t0A+wYp0LWc7ofv+bfrnFMtPtd0yMXFxAyMnq2kDtbSuiDJeAtvQhhnZYs6vWl7JxuzX9BNjdxIZW/t29LQPBEEjlO5fxbAbDq7DY0gfM9z5OnnnCbfIVDMN7hc7QThr1hihBgyd+oVJxRLJGUEvGA7p93N4kSSzv/nqv2OHwYiDHUpPW6jnkzd663CiOC80GdyPvwbGPro6TcWURj7HuJj+gSo7TFslrSg2a0UifQZGndpsmSzYCx38QzJaXKrqHYQGI/dokf7j8x+ObN5RhQck+eftBDeBOLW37euogdJiwNiN4mXM/YZc92e6MEhyfDFjFuiM0Zq8TqFqoO1rRJyuZWFfvE4puGLLqp+aQoMiLHJzTC3nly1ekoHHdVeaLAs6hI7Z6VPBgl/021CtXD/V2/EKQ0gApAD4uqPrxHs2VsiDJlhjOyc5f54zl9WfDBJCFT+tgia6jqWSOuiNE2iZzGzuAuvM13wQbRaYlR6SShb7XUkeEu8GX9PxWsOK1PLQjp2WZz2WT48i+eDEiAlgYDhf4D/KkT+uuIeoJQIGzJkmDPIKlPPvK440SJWYS4QC0O7ya3AMZBdKcXi53CpSt1YDV4H26WJ0b7DIiW5pQoeVEBnXg9UDnb
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: hasura
    type: Opaque
