kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: keycloak-secrets
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  template:
    metadata:
      name: keycloak-secrets
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
    type: Opaque
  encryptedData:
    KEYCLOAK_ADMIN: AgDXwDVpQ2K8CUIluPPSgHIKsrYddZbDRG0WjP5ruX0923tkihqMQVupj8lWXf4Ue1BG3EwEKH/7GKvLJqHk27b4tNWPDAYA4qyfLJ2foLqhCBpNQ1Ia/PJZNStOW8A444tIZ2aJBFdNuKYbsym1x8D0tBJM7P4puGZEnG9tiaW9gMzidjOppXBM3oni/swhqRCiDmIR3a+6Y8K1ULBpOGiiXHoMGSqAxzIN8wZ3NMnU/26oz3bbbRc561gt7vxJsh/FYuRDKdJLCFZSw2aomXqGuXut9v2Bi9t6DmDNgul01zVnB0w/QMW0il0MzyMS4PCKnOastTZ85hgJ6ecEwzKaAzb2p6uu00jizRTv6wECuVTrRDI2djQca8M20HYV/3GuUuLDxfRGTzmDgCLUH5gfKDyJq5GlFJblFJVrnw5xTtt2jxrl8CE9uSoYTrqX1ZSkdKGGEEzqThmwqv1UkJ9X2YvtRVh/0VqXs3Y+1acJMg0ftVqRYjdUbIa6HUT0TlFnUWuLHlhnopd8juVDYEeCr34IMJ6m8YvrfLPOD3n0sleRyCu3oas23hxR7K7M1luC2vq8Jm8+I9XZlyTOVio3XoVUMgw0DUyX2XwpXxHyT9hzbNfnlmF/mu7y8tLP/BjCkGdxN1bPfkbGZclmwLu1toCBet4bup3AcrXGzaX9Dcz6AiRHjaZsbCV+S5ECak4SGswRfOs9gUS/zuNzmdBYZbhqfanxMp1Ni2btlsW9BrKwXNBvk7HrQ3UJ2Q==
    KEYCLOAK_ADMIN_PASSWORD: AgACLIiVnIdYOfnZuJBDYk5f3W6hJ9V2y0c+2A0qUMkuZ+f4I2wGa1463iji/ajaS4gkuPUUt/IUg3CpZNPJ4IH/dptOa5iZ4SvC02MXP850afb0jL3ZwbJHtkmydDzoWWuGsSbXnuKKCj+pEXWzKvp9U7d4T3+8KwoAzEMw97AIlnN6BxH/t1ToecCgd+6v2MgaJwMzbg3ktAoW/dZZXPNoOpE70vkBBc+BhVSXYgV+jouMBNhKzrifpYn2LmFJ3fKcDRd1cMH8dzIj4lxVb3uQHEGupgUQPSEQNlFVZA9YC3z7qn7Jy+PDRw/AajSV5bPKNJKMh+rcyDiXvTTFlUSuvkr2mWkA9wChRXh4LLPU3Vtnye39lrF+HvIeYvlRAG10+64Dv6vzVLDKMbuXwDHkL+tsthv1KL272ewv68RLc1KYjsjJqRrQfnmtkACd4kot+zixaI1EP0a5q/vsp0Ysmedl7GCObWGmgNadWS907cdUuuER5kOUn3Jvi4Lg06vuAZ3PdoGyyN8QAZWUN5rzVtakvag3gXKWrey7Kfp4t3JjWSOWu/vBKwsxOXPgnfwjXdEN/4cxLptWDPpliG7bvd8ug0ZwhksFWxEpIoP1F4gjY7By5aQV4T7lEkpHyEG3K4mNaXaDH6Tb2pRFh/s30YX8KDBXEblWuI4EeV7V18QjTf4jiHlsMxy53tPnsXsj609TDQRmpdE4jNjyoL4Ov8yZHohcmJsKV/ELcWEqsOVWg7+LNAIxJdGG6A==
