apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: keycloak-secrets
spec:
  encryptedData:
    KEYCLOAK_ADMIN: AgBWye/9Iav1llY6ZLWgL4to/75FMWvu21ploogsvNSQoig2vUxNO9e9wpfSf2I8CJDic0RStCI65nvBcJr7UhaV3WXvutbV2JBMgqF6VPGJh1BYu7UERzaBFdfYaV8foFJsLHW5RvPRGALhhiovvR2mjNgNtBdhyf6bmOss+lj/UxN66/vmdBu2PwCRmuyDCCnIbzQw/31KZjA2v9OZC4PLtFB6TTITsZmG6MN5fbz4QFk6TGXDPfYVuN3voFOn1uICcRsk2WY/4N3RYqlhF1vxO974rphuObnzwWOWzfg7dZRx0CdvtbGZsWG4LcMekUHO8mj4gFM1GmS0hkKfQnALattYtfo0Lo42FRFFRm4CSc07BkjW6a/JzEyeYDV+wcZtvcEhLG6UyF9m9eW12ukZyS3K7o/UH/8VR1Z+G65L8KlIpg9gjIXxGyX/cCSFRYt/OvWj5fjpstdAvgcHt4sTlMPaqQpeH3FflRb2VhhXhgBFaXYc0kjl1vDgSV/dCu1OhLcIg1Z4V+z1BAoPESd7syOC9OFxqFacIoK7Uz/vR7svkvFfJrm7Iamnf/CklwuO0BRZrL67Tf1anT4A/WCsFEd/Ha0j9PaxP8UptkfLkDPNICE1qbUkf/vFOQA6d7V2PC+HYkwLrpYnc0Y5ze8gTB4GlOUfQNXGZpaEI9EGguHA7YbAyIXHhyUyYBEeCptdd83u3gaff7RW6Avo/75qT/oiVgUX08eXqp8xo/DRCB/h6JKiAwbpgzADuA==
    KEYCLOAK_ADMIN_PASSWORD: AgBkcJ8Y/h6hIP6OKMl25ryKcL2WTqvRmu6U1wUMvSzI5r+ZJxaMpYNisGgSSDdQmkLGhkMeRmHxfWVSRNSUb5YJ6Aw9MQRHEHXmDDRN8iBuLlpG/uB+rpuILdyKz4z8lxFVUw4ZYd/sR4ge8E+HADVokmFVHPGg+ZDchz7AJ+4qmp/Ey/TRPl47U8xWfLj1P8TpyZCqFgceFoNGLo7OCzhgFAeaiTU0sP2jc1NR0QS0kWK+NhOHZ24AvkQnZo2kPTWY3kFLbh6uz8N7gYif55CIbZSEyfp+OZyfBGzn4xNRe7i004/vDFWhGnAQdaAFDhlc6fHzwIUWTcNUR6E/aA0wX/8HmLKncNQ8UO6UIYOvak0UMT2GnVMkRYaqw2QEKrODbuPwoAJjdrrDxA/s97ZwOSa5iysisa562IMk/dKT6/k4jEdNH0h0PpD4ZE+MYLa8nDNn6yMGeoO4p22U03UjQLzyjMvxWfFLkLTyMy6ct8Lxp++xqm9g58K29dSvXpSxCa1382RjA7ocOqpa4Qy1y4gzVBBvVZLeTXyywqSu4bc3+ZBiAWy1SDadNyin28/krRQ4F7gK7BgzT0cHXPC3xIdI52hsf5Cg9FAZwXd9xBpAMHdkIbrD7/3LvC7FbwjdkqUVX7pjEXfqX0qUHRWjrYcomuRxiBwb+qtWWiqgcMWBiBoddwfdSQudeNHY770LSLtWzNK7j9kFaSDofJPoHdaAO9gP6MpDh03BBpILfmg0YhGp6KrsJDwlHA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: keycloak-secrets
    type: Opaque
