kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: franceconnect
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  template:
    metadata:
      name: franceconnect
      
      creationTimestamp: null
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
    type: Opaque
  encryptedData:
    FRANCE_CONNECT_CLIENT_ID: AgC9DWAggRwIwo2j0Fb/2ElqSHhWsLWptloeofx69CA0nSB/ndm6LVucSyt+J2Jk2G/8gzQeLsuhSEF0aGmbzMTuF7LFSKI9AfMaiXGGU5N9+ujiS4992m7WgIAa0FzKGm9qm0RblNctATEv0uBt0FE28L99wlFkMvCI358alFhaKeokm+Rcf0N2NejtPXg/WM8g5yc9P+QdWEHNabYtU0jAEv7Lj02m7szrQi9bBw94o+t3s06Jtj744YNK+htCz/VQPWEO0pgQ7Bj2MBB61r8+0D77o2I/2nLyR0L3/cJi3ks8JgpfbFiZ2jykeYfBnp7R+risIHDSVELXM1HLEhS3CjvLrA77SCSsAfHVN3o0mJalPimC8JXc0no9YcZzaBk/i9xb05dxFvUn8tfrF/Iq+Qw5My2AOhy/bsJv15xKyOSwPkBtfFgJOhAkohr74lqjZHQBaNefXDVYb67B2tSj4/I7+IIV7gZLLf3ihy4E4F4pp/nInTs8qiswchUu9HKDBmslx8NQcwO81TCH70kbFhgqkfl8cd2Md/Wc5rJC871VY95ClhXQJ4F9beAFGwboJ6mzhNOzbFNKDrG7Ur1M6TCcyjPTDaw1WFK/GoLuPTjUheQ3i76zNAUt9tKda1ePrtP62um2VbGxJLxb0J6gTpmohI6k98Jx7WbbG310rRBuXoVfIP0ODEmUMZs02MmUkCcW0neIk4wWw1xi9hso/H8C4+v2U3K7oKq8+eqVam/h9XJ/o4987+NhtVK79uiERnbf/DBEeVCH1bONHNcp
    FRANCE_CONNECT_CLIENT_SECRET: AgAKll65mcRSgiZU2ps+kmBV4Mn0590PC45mp09pLVGgDUdYqqoz58bGsDjIjIfU0bYOuYWlWhdbIDKL/8nY/s1TzeUc07V4FlOV9rgkSpyJWTakkWIxIZHAlg+SWOIVHN77vqIecGcSYFYqATqkjEk/zwL9cP0ItCKKRCjH4Zw634gYKpcYK/qmaRo/1gKZwjGYf1PTJ3zF94DVvjp0RDKeZik5DPerLFJE8jeElHM39+CGVCT90xRlGF/PvBiQNJ3MZnEblXenXifFOlNWHG6pkWKN5VicRDJJ7mDZD99qdMSkpoWquClcvTtUe0WaohFkBKm7BoblXBYt6PpTB1CqFrVrRPALi0BnOwkSSQqZh40PZ5EaO+i6GfeWPSjKPnuPOxK2iuJP58ZYExcqVN+ABNnPD4UHVxnkvK6BqDaRM42HCbmDEQ+5x3LShtd7dmFKMi14yDoyPAT4VDoY4j1mIAorAo8NCKjUwIuPb9zOizL8CH2Ks/rb0Yj2mO3cjuTDQuAgTytv+b3dHKOPygInq0VfGi97gvxXb5kCP6DxZdMTCilzoKL4qRlUGHwE/uxChu72hhVGBqmJ3e1pA++v253K++T2FsEZmaI3FTAgYMyi0MLAoBEJn1noMC2yIGUB2J3gHFhBqMfguWrmmtOCer9u6IPgG0Xo9Th/z8s7flOomKfvWqJGOgfRIDtcp466Hj6r9gh3ouCVwlEEO6d1ArSfDUpg1LBuHEDUia1LM9Z3UAg5kCwk/PSV2PctO7frEc3Tysau5AiYFPjR6Pjw
