kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: hasura
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  template:
    metadata:
      name: hasura
      
      creationTimestamp: null
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
    type: Opaque
  encryptedData:
    HASURA_GRAPHQL_ADMIN_SECRET: AgABr4dMjHYVnVGQ6p+L0UEVIGbl/J/9LV239rauG4k09g55gHeiwiPvTWC5N9vSCHVPbrQNZmlr1UH2Gn73GHazvhaFhwH4YJ707u58KpJ4kdHwsbQCdzYyScmzMKeTp76mZzHxMMI+8jxWFCXz6m1+JF8O/JpRHUyGqjM8itCjnYu6rOQ7zr83dTXJ0eQYOB7oPKvmx8kgjSDoMktZLPNsQAqJbI4Zpyi1l0LHv79ze/n+4CG8KOAqyzIib0RDiWdMZ039tDe2Vz3lbkuoSBID/fD04BETaCFxrjU5nybrGx+g0nIFGUd3kmk7W9bXQ/UBQMKOpqXlzbdu131IZxBr0t70Z3vwgKpsK5FJa8wZCv6c+X+A5103z7Q05HHHB1ROBzl+u6i54Qh1ByQ6JNSlxrlbjMrF4BI2Fbn2jUrIcUt9MGoVV9OB09uzpDDZ/6WVrAvlX5A8sUwj3t49fGRRJKaBofu0DYb7zP/JHJRNntrVcd0WQA0v2CIOPrVAN1WCvM58Cc5ldqC5gkZ7H9kaGiGGNMSFDMcT+ox8WwXp/adcxzz9PjwjER4Sa5I5v5rPUD5yFf+pQNEEjTUtpvTDJ4bNSgAqN+xKVDjtRqFYkXvXcF+P7Iw5M8FRrmzrSOc2SaZcx2vh6cD58YruargxADWv4ERc4lzc8mMFghsBNBJYYB4raS7HyJAwNDI2mCZQ4FYqR6Dayo2r/wWPqszR/Equ
