apiVersion: v1
kind: Secret
metadata:
  name: app
type: Opaque
stringData:
  NEXTAUTH_SECRET: somethingVeryLongAndS3cr3t
  KEYCLOAK_CLIENT_ID: somethingVeryLongAndS3cr3t
  KEYCLOAK_CLIENT_SECRET: somethingVeryLongAndS3cr3t
