# here you can customize your deployment according to : https://github.com/SocialGouv/actions/blob/master/autodevops-helm-deploy/chart/values.yaml
app:
  enabled: true
  probesPath: /healthz

keycloak:
  postgresql:
    enabled: false

  statefulsetAnnotations:
    kapp.k14s.io/nonce: ""
    kapp.k14s.io/update-strategy: fallback-on-replace
    kapp.k14s.io/change-group: "kube-workflow/keycloak.{{ .Values.global.namespace }}"
    kapp.k14s.io/disable-original: ""
    kapp.k14s.io/create-strategy: fallback-on-update

  extraEnvFrom: |
    - secretRef:
        name: keycloak-db
    - secretRef:
        name: keycloak-secrets

  extraEnv: |
    - name: KEYCLOAK_IMPORT
      value: /realm/realm.json
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"
    - name: DB_VENDOR
      value: postgres
    - name: DB_ADDR
      value: "$(PGHOST)"
    - name: DB_PORT
      value: "5432"
    - name: DB_DATABASE
      value: "$(PGDATABASE)"
    - name: DB_USER
      value: "$(PGUSER)"
    - name: DB_PASSWORD
      value: "$(PGPASSWORD)"
    - name: JAVA_OPTS
      value: -Dkeycloak.profile=preview

  extraVolumes: |
    - name: keycloak-realm-tpl
      configMap:
        name: keycloak-realm
    - name: keycloak-realm
      emptyDir: {}

  extraVolumeMounts: |
    - name: keycloak-realm
      mountPath: "/realm/"
      readOnly: true
    - name: extensions
      mountPath: /opt/keycloak/providers

  extraInitContainers: |
    - name: realm-ext-provider
      image: curlimages/curl
      imagePullPolicy: IfNotPresent
      command:
        - sh
      args:
        - -c
        - curl -L -f -S -o /extensions/keycloak-dsfr-1.0.1.jar https://github.com/SocialGouv/keycloak-dsfr/releases/latest/download/keycloak-theme.jar
      volumeMounts:
        - name: extensions
          mountPath: /extensions

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
      kubernetes.io/ingress.class: nginx
    tls:
      - hosts:
          - "keycloak-{{ .Values.global.host }}"
        secretName: wildcard-crt
    rules:
      - host: "keycloak-{{ .Values.global.host }}"
        paths:
          - path: /
            pathType: Prefix
