import type { NextPage } from "next";
import Head from "next/head";
import { Footer, Header } from "@components";

const Home: NextPage = () => {
  return (
    <div style={{ height: "800px" }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      yooooo
    </div>
  );
};

export default Home;
