projectName: fabrique

dependencies:
  fabrique:
    import: SocialGouv/kontinuous/plugins/fabrique
  contrib:
    deployWith:
      kapp:
        options:
          kubeApiQps: 10
          kubeApiBurst: 10
