projectName: fabrique
ciNamespace: ci-fabrique

dependencies:
  fabrique:
    extends:
      - name: ovh
        ifEnv: [dev, preprod]
      - name: buildkit-service
        ifEnv: [dev, preprod]
    dependencies:
      contrib:
        preDeploy:
          importSecrets:
            options:
              secrets:
                tumeplay-dev-backups-access-key:
