projectName: fabrique

dependencies:
  fabrique:
    import: SocialGouv/kontinuous/plugins/fabrique
    dependencies:
      contrib:
        deployWith:
          kapp:
            options:
              kubeApiQps: 10
              kubeApiBurst: 10
