projectName: fabrique

dependencies:
  fabrique:
    import: SocialGouv/kontinuous/plugins/fabrique
    dependencies:
      contrib:
        patches:
          needsUsingInitcontainers:
            enabled: true
          needsUsingKapp:
            enabled: false
        deployWith:
          kapp:
            enabled: false
          helm:
            enabled: true
            