projectName: fabrique
ciNamespace: ci-fabrique

dependencies:
  fabrique:
    extends:
      - name: ovh
        ifEnv: [dev, preprod]
      - name: buildkit-service
        ifEnv: [dev, preprod]
    dependencies:
      contrib:
        preDeploy:
          importSecrets:
            options:
              secrets:
                kubeconfig:
                harbor:
                buildkit-client-certs:
                fabrique-dev-backups-access-key:
# links:
#   socialgouv/helm-charts/charts/pgweb@v1: /Users/julienb/projects/mas/helm-charts/charts/pgweb
