projectName: fabrique
#isLocal: true
#gitBranch: local
deployTimeout: 30m

dependencies:
  fabrique:
    import: SocialGouv/kontinuous/plugins/fabrique
    dependencies:
      contrib:
        validators:
          noPlainSecrets: # should be enable for lebal environment
            enabled: false
