projectName: fabrique

dependencies:
  fabrique:
    import: SocialGouv/kontinuous/plugins/fabrique
    dependencies:
      contrib:
        validators:
          sealedSecrets:
            options:
              clusters:
                dev:
                  kubesealEndpoint: "https://kubeseal.ovh.fabrique.social.gouv.fr"
