projectName: fabrique
ciNamespace: ci-fabrique

dependencies:
  fabrique:
    extends:
      - name: ovh
      - name: buildkit-service
    dependencies:
      contrib:
        preDeploy:
          importSecrets:
            options:
              secrets:
                fabrique-dev-backups-access-key:
                fabrique-prod-backups-access-key:
