projectName: fabrique

# deployWithPlugin: kapp
# deployWithPlugin: helm
deployWithPlugin: kubectl

dependencies:
  fabrique:
    import: SocialGouv/kontinuous/plugins/fabrique
    dependencies:
      contrib:
        preDeploy:
          namespaces:
            enabled: true
        postDeploy:
          waitRollout:
            enabled: true
        deploySidecars:
          failfast:
            enabled: false
          stern:
            enabled: true
        patches:
          needsUsingInitcontainers:
            enabled: true
          needsUsingKapp:
            enabled: false
          filterDisableKapp:
            enabled: true
          # helm:
          #   enabled: true
        # deployWith:
        #   kapp:
        #     options: {}
        #   helm:
        #     options: {}
            