# main app container
app:
  ~chart: app
  host: "{{.Values.global.host}}"
  imagePackage: app
  containerPort: 3000
  probesPath: "/healthz"
  envFrom:
    - configMapRef:
        name: app
    - secretRef:
        name: app
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"

jobs:
  runs:
    build-app:
      use: build
      with:
        imagePackage: app
        # pass a custom docker build arg
        buildArgs:
          GITHUB_SHA: "{{ $.Values.global.sha }}"
          NEXT_PUBLIC_SITE_URL: "https://{{ $.Values.global.host }}"
          NEXT_PUBLIC_HASURA_GRAPHQL_ENDPOINT_URL: "https://hasura-{{.Values.global.host}}/v1/graphql"
