global:
  registry: harbor.fabrique.social.gouv.fr

app-front:
  needs: [build-app]
  imageProject: fabrique
  imageRepository: template
  imagePackage: app
  containerPort: 8080
  probesPath: "/healthz"
  envFrom:
    - configMapRef:
        name: app
    - secretRef:
        name: app

jobs:
  runs:
    build-app:
      use: SocialGouv/kontinuous/plugins/fabrique/jobs/build@v1
      with:
        imageProject: fabrique
        imageRepository: template
        imagePackage: app
        registrySecretRefName: harbor
        buildArgs:
          GITHUB_SHA: "{{ $.Values.global.sha }}"

keycloakx:
  fullnameOverride: "keycloakx"
  serviceAccount:
    create: false

  database:
    vendor: postgres

  ærgs:
    [
      "start-dev",
      "--auto-build",
      "--db=postgres",
      "--import-realm",
      "--features",
      "admin2",
    ]

  statefulsetAnnotations:
    kapp.k14s.io/nonce: ""
    kapp.k14s.io/update-strategy: fallback-on-replace
    kapp.k14s.io/change-group: "kontinuous/keycloak.{{ .Values.global.namespace }}"
    kapp.k14s.io/disable-original: ""
    kapp.k14s.io/create-strategy: fallback-on-update

  extraEnvFrom: |
    - secretRef:
        name: pg-user-keycloak
    - secretRef:
        name: keycloak-secrets
  extraEnv: |
    - name: KC_DB_URL,
      value: "jdbc:$(DATABASE_URL)"
    - name: KC_DB
      value: postgres
    - name: KC_METRICS_ENABLED
      value: "true"
    - name: KC_DB_USERNAME
      value: "$(PGUSER)"
    - name: KC_DB_PASSWORD
      value: "$(PGPASSWORD)"
    - name: KC_LOG_LEVEL
      value: INFO
  extraVolumes: |
    - name: keycloak-realm-tpl
      configMap:
        name: keycloak-realm
    - name: keycloak-realm
      emptyDir: {}
    - name: providers
      emptyDir: {}
  extraVolumeMounts: |
    - name: keycloak-realm
      mountPath: "/opt/keycloak/data/import"
      readOnly: true
    - name: providers
      mountPath: "/opt/keycloak/providers"
  extraInitContainers: |
    - name: compile-realm
      image: hairyhenderson/gomplate:v3.10.0-alpine
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - name: keycloak-realm-tpl
        mountPath: "/realm-tpl/"
        readOnly: true
      - name: keycloak-realm
        mountPath: "/realm/"
      envFrom:
      - configMapRef:
          name: app
      - secretRef:
          name: app
      - secretRef:
          name: franceconnect
      - secretRef:
          name: smtp
      command:
        - sh
      args:
        - -c
        - "cat /realm-tpl/realm.json.envtpl | gomplate > /realm/realm.json"
    - name: fetch-keycloak-providers
      image: curlimages/curl
      imagePullPolicy: IfNotPresent
      command:
        - sh
      args:
        - -c
        - curl -L -f -S -o /providers/keycloak-dsfr-latest.jar https://github.com/SocialGouv/keycloak-dsfr/releases/latest/download/keycloak-theme.jar -o /providers/keycloak-franceconnect-4.1.0.jar https://github.com/InseeFr/Keycloak-FranceConnect/releases/download/4.1.0/keycloak-franceconnect-4.1.0.jar
      volumeMounts:
        - name: providers
          mountPath: /providers

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
      kubernetes.io/ingress.class: nginx
    tls:
      - hosts:
          - "keycloak-{{ .Values.global.host }}"
        secretName: wildcard-crt
    rules:
      - host: "keycloak-{{ .Values.global.host }}"
        paths:
          - path: /
            pathType: Prefix
