# define docker registry options
global:
 # registry: harbor.fabrique.social.gouv.fr
  imageProject: fabrique
  imageRepository: template

# main app container
app:
  # wait for build-app before deployment
  ~needs: [build-app]
  imagePackage: app
  containerPort: 8080

jobs:
  runs:
    # define a kubernetes job to build the docker image
    build-app:
      use: build
      with:
        imagePackage: app
     #   registrySecretRefName: harbor
      #  buildOptions: --single-snapshot --ignore-path=/product_uuid --compressed-caching=false # optim for local builds
        # pass a custom docker build arg
        buildArgs:
          GITHUB_SHA: "{{ $.Values.global.sha }}"
          NEXT_PUBLIC_SITE_URL: "https://{{ $.Values.global.host }}"
