global:
  registry: harbor.fabrique.social.gouv.fr

app:
  needs: [build-app]
  imageProject: fabrique     # optional
  imageRepository: template  # optional
  imagePackage: app          # mandatory
  containerPort: 8080        # optional, default = 3000

jobs:
  runs:
    build-app:
      use: SocialGouv/kontinuous/plugins/fabrique/jobs/build@master
      with:
        imageProject: fabrique.         # optional
        imageRepository: template       # optional
        imagePackage: app
        registrySecretRefName: harbor
        buildArgs:
          GITHUB_SHA: "{{ $.Values.global.sha }}"

