# main app container
app:
  # wait for build-app before deployment
  ~chart: app
  ~needs: [build-app]
  containerPort: 8080
  securityContext:
    fsGroup: 101
    runAsUser: 101
    runAsGroup: 101

jobs:
  runs:
    # define a kubernetes job to build the docker image
    build-app:
      use: build
      with:
        imagePackage: app
        # pass a custom docker build arg
        buildArgs:
          GITHUB_SHA: "{{ $.Values.global.sha }}"
          NEXT_PUBLIC_SITE_URL: "https://{{ $.Values.global.host }}"
