global:
  registry: harbor.fabrique.social.gouv.fr
  imageProject: fabrique
  imageRepository: template

app:
  needs: [build-app]
  imagePackage: app
  containerPort: 8080

jobs:
  runs:
    build-app:
      use: SocialGouv/kontinuous/plugins/contrib/jobs/build@skipExisting
      with:
        imagePackage: app
        registrySecretRefName: harbor
        skipExisting: true
        buildOptions: --single-snapshot --ignore-path=/product_uuid --compressed-caching=false # optim for local builds
        buildArgs:
          GITHUB_SHA: "{{ $.Values.global.sha }}"
