# main app container
app:
  # wait for build-app before deployment
  ~needs: [build-app]
  imagePackage: app
  containerPort: 8080
  image: ghcr.io/socialgouv/docker/nginx:feat-nginx-kube-zero-downtime
  livenessProbe:
    httpGet:
      path: /live
      port: 8080
  readinessProbe:
    httpGet:
      path: /ready
      port: 8080
  lifecycle:
    preStop:
      exec:
        command: ["/pre-stop.sh", "10"]

jobs:
  runs:
    # define a kubernetes job to build the docker image
    build-app:
      use: build
      with:
        imagePackage: app
        # pass a custom docker build arg
        buildArgs:
          GITHUB_SHA: "{{ $.Values.global.sha }}"
          NEXT_PUBLIC_SITE_URL: "https://{{ $.Values.global.host }}"
