global:
  registry: harbor.fabrique.social.gouv.fr
  
app:
  needs: [build-app]
  imagePackage: app
  containerPort: 8080

jobs:
  runs:
    build-app:
      use: SocialGouv/kontinuous/plugins/fabrique/jobs/build@master
      with:
        imagePackage: app
        buildArgs:
          GITHUB_SHA: "{{ $.Values.global.sha }}"

