name: ♻️ Deactivate
on:
  pull_request:
    types: [closed]

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.ref }}

jobs:
  kontinuous:
    uses: socialgouv/workflows/.github/workflows/use-ks-gh-deactivate.yaml@v1
    secrets: inherit
