name: Deploy demo

on:
  push:
    branches: [main, next]

concurrency:
  cancel-in-progress: true
  group: deploy-${{ github.ref }}

jobs:
  build:
    name: Deployment demo on gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install dependencies
        run: |
          yarn --immutable

      - name: Build
        run: |
          yarn build

      # deploy build to gh-pages
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.9
        with:
          branch: gh-pages
          folder: out
