name: Deploy
on:
  push:
    branches:
      - "**"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.ref }}

jobs:
  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    steps:
      - name: Use kontinuous deployment
        uses: SocialGouv/kontinuous/.github/actions/deploy-via-github@v1
        with:
          environment: dev
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherProjectId: ${{ secrets.RANCHER_PROJECT_ID }}
          ciNamespace: ${{ secrets.RANCHER_PROJECT_NAME }}-ci
          disableDiff: true
