name: Preproduction

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*

concurrency:
  cancel-in-progress: true
  group: preproduction

jobs:
  follow-deployment:
    uses: SocialGouv/kontinuous/.github/workflows/workflow-webhook.yaml@v1
    secrets: inherit
