name: Production

on:
  push:
    tags:
      - v*

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  follow-deployment:
    environment:
      name: production
      url: https://template.fabrique.social.gouv.fr
    uses: SocialGouv/kontinuous/.github/workflows/workflow-logs.yaml@v1
    secrets: inherit
