name: Review

on:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - v*

concurrency:
  cancel-in-progress: true
  group: review-${{ github.ref }}

jobs:
  follow-deployment:
    uses: SocialGouv/kontinuous/.github/workflows/workflow-logs.yaml@v1.49.0
    secrets: inherit
