name: Review

on:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - v*

concurrency:
  cancel-in-progress: true
  group: review-${{ github.ref }}

jobs:
  register-app:
    name: Build & Register application
    runs-on: ubuntu-latest
    steps:
      - name: Get host name
        run: |
          REPOSITORY=${GITHUB_REPOSITORY#*/}
          BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          HOST=$(npx kontinuous slugify $REPOSITORY-$BRANCH)
          echo "HOST=${HOST}" >> $GITHUB_ENV

      - name: Use autodevops build and register
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          imagePackage: app
          dockerbuildargs: |
            NEXT_PUBLIC_APP_VERSION_COMMIT=${{ env.GITHUB_SHA }}"
            NEXT_PUBLIC_HASURA_GRAPHQL_ENDPOINT_URL=https://hasura-${{ env.HOST }}.dev.fabrique.social.gouv.fr/v1/graphql

  register-hasura:
    name: Build & Register Hasura
    runs-on: ubuntu-latest
    steps:
      - name: Use autodevops build and register
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          imagePackage: hasura
          dockerfile: ./hasura/Dockerfile
          dockercontext: ./hasura

  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    needs: [register-app, register-hasura]
    steps:
      - name: Use kontinuous deployment
        uses: SocialGouv/kontinuous/.github/actions/deploy-via-github@v1
        with:
          environment: dev
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherProjectId: ${{ secrets.RANCHER_PROJECT_ID }}
          ciNamespace: ${{ secrets.RANCHER_PROJECT_NAME }}-ci
          disableDiff: true
