name: Storybook

on:
  push:
    branches: [main]

concurrency:
  cancel-in-progress: true
  group: storybook-${{ github.ref }}

jobs:
  storybook:
    name: Deployment storybook on gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install dependencies
        run: |
          yarn --immutable

      - name: Deploy
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          yarn storybook:deploy:action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
